// Angular 2
import 'zone.js';
import 'reflect-metadata';
import 'rxjs';
import '@angular/core';
import '@angular/common';
import '@angular/compiler';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/http';
import '@angular/router';
import '@angular2-material/menu';
import '@angular2-material/toolbar';
import '@angular2-material/sidenav';
import '@angular2-material/card';
import '@angular2-material/button';
import '@angular2-material/icon';
import '@angular2-material/list';
import '@angular/material';
